# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    groups:
      typescript:
        patterns:
          - "@voxpelli/tsconfig"
          - "typescript"
          - "@types/node"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
